name: sqlfluff

on:
  pull_request:
    paths:
      - "dags/sql/**"

  workflow_dispatch: {}

jobs:
  lint-models:
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - uses: "actions/setup-python@v4"
        with:
            python-version: "3.11"

      - name: Install SQLFluff
        run: "pip install sqlfluff"

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v34
        with:
          files: |
            dags/sql/**

      - name: Lint changed SQL files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "sqlfluff lint $file"
            # sqlfluff lint $file
          done
