name: sqlfluff

on:
  pull_request:
    paths:
      - "dags/sql/**"

  workflow_dispatch: {}

jobs:
  lint-models:
    runs-on: ubuntu-latest
    env:
      REVIEWDOG_GITHUB_API_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
    steps:
      - uses: "actions/checkout@v3"
        with:
          fetch-depth: 0

      - uses: "actions/setup-python@v4"
        with:
            python-version: "3.11"

      - name: Install SQLFluff
        run: "pip install sqlfluff"

      - name: Lint changed SQL files
        run: |
          diff-quality \
            --violations sqlfluff \
            --fail-under 100 \
            --compare-branch remotes/origin/main \
            --include "dags/sql/**"

      - uses: reviewdog/action-setup@v1

      - name: Format files
        run: |
          sqlfluff fix dags/sql/ -f
          TMPFILE=$(mktemp)
          git diff >"${TMPFILE}"
          cat ${TMPFILE}
          git stash -u && git stash drop
          reviewdog -f=diff --name=sqlfluff -f.diff.strip=1 -reporter="github-pr-review" < "${TMPFILE}"

      # - name: Update Pull Request
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ inputs.github-token }}
